print('Boas vindas ao nosso glorioso jogo de MADLIB')
substantivo = input('Digite um NOME: ')
adjetivo = input('Digite um ADJETIVO: ')
verbo = input('Digite um VERBO: ')
objeto = input('Digite um OBJETO: ')
profissao = input('Digite uma PROFISSÃO: ')
adjetivo2 = input('Digite um outro ADJETIVO: ')
numero = input('Digite um NÚMERO: ')
animal = input('Digite um ANIMAL: ')
objeto2 = input('Digite um outro OBJETO: ')
objeto3 = input('Digite um outro OBJETO: ')

print()
print('A Grande Aventura no Escritório de Tecnologia')
print()
print("Um dia, o(a) " + substantivo + " estava trabalhando em um projeto super " + adjetivo + ". De repente, o computador começou a " + verbo + " sozinho!")
print("Sem pensar duas vezes, o(a) " + substantivo + " pegou seu " + objeto + " e começou a digitar comandos como um(a) verdadeiro(a) " + profissao + ".")
print('"Preciso consertar isso antes que o sistema fique ' + adjetivo2 + '!" exclamou o(a) ' + substantivo + '. Depois de ' + numero + ' tentativas, finalmente o computador respondeu: "O problema foi causado por um(a) ' + animal + ' que estava no sistema!"')
print("Com isso, o problema foi resolvido, e o(a) " + substantivo + " ganhou o prêmio de " + objeto2 + " mais inovador do ano.")
print("Moral da história: sempre leve seu(sua) " + objeto3 + " para o escritório, porque nunca se sabe quando você vai precisar!")